// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwntsqetqyoxphcxcmxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3bnRzcWV0cXlveHBoY3hjbXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzkwOTgsImV4cCI6MjA2MDk1NTA5OH0.XoG5dXVjlLFbey_u3NpQzLK1-Zdp6JdmhZYqVJ1Cteg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);